#**[Teaching Machines to Understand Sign Language](https://www.sciencebuddies.org/)**

This notebook was developed by Science Buddies [www.sciencebuddies.org](https://www.sciencebuddies.org/) as part of a science project to allow students to explore and learn about artificial intelligence. For personal use, this notebook can be downloaded and modified with attribution. For all other uses, please see our [Terms and Conditions of Fair Use](https://www.sciencebuddies.org/about/terms-and-conditions-of-fair-use).  

**Troubleshooting tips**
*   Read the written instructions at Science Buddies and the text and comments on this page carefully.
*   If you make changes that break the code, you can download a fresh copy of this notebook and start over.

*   If you are using this notebook for a science project and need help, visit our [Ask an Expert](https://www.sciencebuddies.org/science-fair-projects/ask-an-expert-intro) forum for assistance.

## **How To Use This Notebook**

This notebook contains text fields, like this one, that give you information about the project and instructions.

In [1]:
# There are also code blocks, like this one.

# The green text in a code block are comments. Comments are descriptions of what the code does.

# The non-green text in a code block is the Python code. Click on the triangle in the top left corner to run this code block.

print("Congratulations, you ran a code block! Try changing the text in the code and running it again.")

Congratulations, you ran a code block! Try changing the text in the code and running it again.

# Installing Dependencies

In [4]:
# !pip uninstall -y mediapipe
# !pip install -U "numpy<2" "protobuf<5"
# !pip install --no-cache-dir "mediapipe==0.10.21"
!pip uninstall -y jax jaxlib mediapipe numpy ml_dtypes
!pip install numpy==1.26.4
!pip install ml_dtypes==0.3.2
!pip install mediapipe==0.10.14 --no-deps

Found existing installation: jax 0.10.0
Uninstalling jax-0.10.0:
  Successfully uninstalled jax-0.10.0
Found existing installation: jaxlib 0.10.0
Uninstalling jaxlib-0.10.0:
  Successfully uninstalled jaxlib-0.10.0
Found existing installation: mediapipe 0.10.14
Uninstalling mediapipe-0.10.14:
  Successfully uninstalled mediapipe-0.10.14
Found existing installation: numpy 2.4.4
Uninstalling numpy-2.4.4:
  Successfully uninstalled numpy-2.4.4
Found existing installation: ml_dtypes 0.5.4
Uninstalling ml_dtypes-0.5.4:
  Successfully uninstalled ml_dtypes-0.5.4
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.16.1 requires ml-dtypes~=0.3.1, which is not installed.
keras 3.13.2 requires ml-dtypes, which is not installed.
flax 0.11.2 requires jax>=0.6.0, which is not installed.
tensorstore 0.1.82 requires ml_dtypes>=0.5.0, which is not installed.
orbax-checkpoint 0.11.36 requires jax>=0.6.0, which is not installed.
keras-hub 0.26.0 requires tensorflow-text; platform_system != "Windows", which is not installed.
dopamine-rl 4.1.2 requires jax>=0.1.72, which is not installed.
dopamine-rl 4.1.2 requires jaxlib>=0.1.51, which is not installed.
dopamine-rl 4.1.2 requires opencv-python>=3.4.8.29, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
optax 0.2.8 requires jax>=0.5.3, which is not installed.
optax 0.2.8 requires jaxlib>=0.5.3, which is not installed.
tensorflow-hub 0.16.1 requires tf-keras>=2.14.1, which is not installed.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
grain 0.2.16 requires protobuf>=5.28.3, but you have protobuf 4.25.9 which is incompatible.
shap 0.51.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

Collecting ml_dtypes==0.3.2
  Using cached ml_dtypes-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: numpy>1.20 in /usr/local/lib/python3.12/dist-packages (from ml_dtypes==0.3.2) (1.26.4)
Using cached ml_dtypes-0.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
Installing collected packages: ml_dtypes
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
orbax-checkpoint 0.11.36 requires jax>=0.6.0, which is not installed.
keras-hub 0.26.0 requires tensorflow-text; platform_system != "Windows", which is not installed.
dopamine-rl 4.1.2 requires jax>=0.1.72, which is not installed.
dopamine-rl 4.1.2 requires jaxlib>=0.1.51, which is not installed.
dopamine-rl 4.1.2 requires opencv-python>=3.4.8.29, which is not installed.
dopamine-rl 4.1.2 requires tf-keras>=2.18.0, which is not installed.
tensorstore 0.1.82 requires ml_dtypes>=0.5.0, but you have ml-dtypes 0.3.2 which is incompatible.
Successfully installed ml_dtypes-0.3.2
Collecting mediapipe==0.10.14
  Using cached mediapipe-0.10.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.7 kB)
Using cached mediapipe-0.10.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.7 MB)
Installing collected packages: mediapipe
Successfully installed mediapipe-0.10.14

In [3]:
# This command installs the TensorFlow library using pip (Python's package installer)
# !pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Collecting protobuf>=5.28.0 (from tensorflow)
  Using cached protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.26.4)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Using cached protobuf-7.34.1-cp310-abi3-manylinux2014_x86_64.whl (324 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.9
    Uninstalling protobuf-4.25.9:
      Successfully uninstalled protobuf-4.25.9
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires opencv-python>=3.4.8.29, which is not installed.
mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 7.34.1 which is incompatible.
google-cloud-aiplatform 1.148.1 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 7.34.1 which is incompatible.
google-cloud-bigtable 2.36.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.1 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.34.1 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
google-cloud-discoveryengine 0.13.12 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
Successfully installed protobuf-7.34.1

In [4]:
# Install the OpenCV library, which is used for computer vision tasks such as image and video processing.
# !pip install opencv-python

# !pip uninstall -y cv2 opencv-python opencv-python-headless
# !pip install --no-cache-dir opencv-python-headless

WARNING: Skipping cv2 as it is not installed.
WARNING: Skipping opencv-python as it is not installed.
Found existing installation: opencv-python-headless 4.13.0.92
Uninstalling opencv-python-headless-4.13.0.92:
  Successfully uninstalled opencv-python-headless-4.13.0.92
Collecting opencv-python-headless
  Downloading opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (19 kB)
Collecting numpy>=2 (from opencv-python-headless)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Downloading opencv_python_headless-4.13.0.92-cp37-abi3-manylinux_2_28_x86_64.whl (60.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 MB 205.5 MB/s eta 0:00:00
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 176.7 MB/s eta 0:00:00
Installing collected packages: numpy, opencv-python-headless
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dopamine-rl 4.1.2 requires opencv-python>=3.4.8.29, which is not installed.
mediapipe 0.10.21 requires numpy<2, but you have numpy 2.4.4 which is incompatible.
mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 7.34.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 7.34.1 which is incompatible.
Successfully installed numpy-2.4.4 opencv-python-headless-4.13.0.92

# 1. Importing Libraries

In [2]:
# General libraries
import os  # For interacting with the operating system (e.g., file handling)
import time  # For time-related functions
import numpy as np  # For numerical operations and handling arrays
import scipy.stats  # For statistical functions (e.g., mode, z-test)
import random
import pandas as pd

# Visualization libraries
import matplotlib.pyplot as plt  # For plotting graphs and images
from IPython.display import display, Image  # For displaying images and other media in Jupyter/Colab

# Computer Vision Libraries
import cv2  # For computer vision tasks such as image and video processing
import mediapipe as mp  # For using MediaPipe's machine learning models for pose detection and more
from google.colab.patches import cv2_imshow  # For displaying images with OpenCV in Google Colab

# Machine Learning Libraries
from sklearn.model_selection import train_test_split  # For splitting data into training and testing sets
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score  # For model evaluation

# Deep Learning Libraries (TensorFlow and Keras)
from tensorflow.keras.utils import to_categorical  # For converting labels to categorical format (one-hot encoding)
from tensorflow.keras.models import Sequential  # For defining the neural network architecture
from tensorflow.keras.layers import LSTM, Dense  # For adding LSTM and Dense layers to the model
from tensorflow.keras.callbacks import TensorBoard  # For logging training progress for TensorBoard
from tensorflow.keras.models import load_model  # For loading pre-trained models

In [3]:
# Import the 'drive' module from Google Colab to interact with Google Drive
from google.colab import drive

# Mount Google Drive to access files stored in it. This will create a folder 'drive' in the '/content' directory.
# After running this, you will be prompted to authorize Colab to access your Google Drive.
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [4]:
# Set the base directory to the specified path on Google Drive.
# This is the location where the 'sign_language_detection' folder is stored within the 'MyDrive' folder.
base_dir = "/content/drive/MyDrive/sign_language_detection"

test_videos_path = os.path.join(base_dir, 'test_videos')
if not os.path.exists(test_videos_path):
    os.makedirs(test_videos_path)

DATA_PATH = os.path.join(base_dir, 'MP_Data')

# 2. Detecting Keypoints using MP Holistic

Code Block 2A

In [5]:
# Initialize the Holistic model from MediaPipe for full-body pose detection.
# This model can detect landmarks for the face, hands, and body.
mp_holistic = mp.solutions.holistic

# Initialize the drawing utilities from MediaPipe to draw the landmarks on images or videos.
# These utilities help visualize the pose detection results by drawing the keypoints and connections.
mp_drawing = mp.solutions.drawing_utils

# This function processes an image using a MediaPipe model to detect landmarks/poses and returns the processed image and the results.
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

# This function draws the detected pose, left hand, and right hand landmarks with their connections on the given image.
def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

# This function draws the pose, left hand, and right hand landmarks with custom styling (color, thickness, and circle radius)
# on the given image, using the MediaPipe Holistic model's results.
def draw_styled_landmarks(image, results):
    # Draw pose connections
    mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                             mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                             )
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             )
    # Draw right hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS,
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             )

Code Block 2B

In [6]:
# TODO: Change the name of the test video to ensure the code is running
video_name = "test_video_1.mov"
video_path = os.path.join(test_videos_path, video_name)

# Try to open the video
cap = cv2.VideoCapture(video_path)

# Check if the video opened successfully
if not cap.isOpened():
    raise FileNotFoundError(
        f"Error: Cannot open video file '{video_path}'. Please check if the file exists and the path is correct."
    )

# Set MediaPipe model
mp_holistic = mp.solutions.holistic

# Use the same frame selection logic as Section 5
target_frame_count = sequence_length if "sequence_length" in globals() else 30
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

print("Video:", video_path)
print("Total frames:", total_frames)
print("Selected frames:", target_frame_count)

if total_frames < 2:
    cap.release()
    raise ValueError("Video does not have enough frames.")

frame_indices = np.linspace(0, total_frames - 2, target_frame_count, dtype=int)

with mp_holistic.Holistic(
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
) as holistic:

    for frame_num, frame_index in enumerate(frame_indices):
        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)

        ret, frame = cap.read()

        if not ret:
            print(f"⚠ Could not read selected frame {frame_num} / original frame {frame_index}")
            continue

        # Do NOT flip vertically
        # frame = cv2.flip(frame, 0)

        # Make detections
        image, results = mediapipe_detection(frame, holistic)

        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Convert BGR to RGB for Colab display
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        # Display every selected frame
        plt.figure(figsize=(8, 8))
        plt.imshow(image_rgb)
        plt.axis("off")
        plt.title(f"Selected frame {frame_num} / 29 | Original frame {frame_index}")
        display(plt.gcf())
        plt.close()

cap.release()

Output hidden; open in https://colab.research.google.com to view.

# 3. Extracting Keypoint Values

Code Block 3A

In [7]:
# Extract keypoints safely from MediaPipe Holistic results
# Output length = 1662

def extract_keypoints(results):
    pose = np.array([
        [res.x, res.y, res.z, res.visibility]
        for res in results.pose_landmarks.landmark
    ]).flatten() if results.pose_landmarks else np.zeros(33 * 4)

    face = np.array([
        [res.x, res.y, res.z]
        for res in results.face_landmarks.landmark
    ]).flatten() if results.face_landmarks else np.zeros(468 * 3)

    lh = np.array([
        [res.x, res.y, res.z]
        for res in results.left_hand_landmarks.landmark
    ]).flatten() if results.left_hand_landmarks else np.zeros(21 * 3)

    rh = np.array([
        [res.x, res.y, res.z]
        for res in results.right_hand_landmarks.landmark
    ]).flatten() if results.right_hand_landmarks else np.zeros(21 * 3)

    return np.concatenate([pose, face, lh, rh])

# 4. Setting up Folders for Collection

Code Block 4A

In [12]:
# Define the set of actions/signs to detect
actions = np.array(['hello', 'thank_you', 'see_you_later'])

# Paths
DATA_PATH = os.path.join(base_dir, 'MP_Data')
VIDEO_PATH = os.path.join(base_dir, 'training_videos')

# Number of frames extracted from each video
sequence_length = 30

# Create main folders
os.makedirs(DATA_PATH, exist_ok=True)
os.makedirs(VIDEO_PATH, exist_ok=True)

# Create one folder per action
for action in actions:
    os.makedirs(os.path.join(DATA_PATH, action), exist_ok=True)
    os.makedirs(os.path.join(VIDEO_PATH, action), exist_ok=True)

print("DATA_PATH:", DATA_PATH)
print("VIDEO_PATH:", VIDEO_PATH)
print("Actions:", actions)
print("Sequence length:", sequence_length)

DATA_PATH: /content/drive/MyDrive/sign_language_detection/MP_Data
VIDEO_PATH: /content/drive/MyDrive/sign_language_detection/videos
Actions: ['hello' 'thank_you' 'see_you_later']
Sequence length: 30

# 5. Collecting Keypoint Values for Training and Testing

Code Block 5A

In [13]:
# Process videos and save extracted keypoints dynamically
# Clears old MP_Data for each action before regenerating

import shutil
import time

target_frame_count = sequence_length
video_extensions = (".mp4", ".mov", ".avi", ".mkv")

# Set True if you want to visualize extracted frames
debug_visualization = False

# Which extracted frames to display when debugging
frames_to_show = [0, 5, 10, 15, 20, 25, 29]

for action in actions:

    action_video_path = os.path.join(VIDEO_PATH, action)
    action_data_path = os.path.join(DATA_PATH, action)

    os.makedirs(action_video_path, exist_ok=True)

    # Clear old extracted keypoint data for this action
    if os.path.exists(action_data_path):
        shutil.rmtree(action_data_path)

    os.makedirs(action_data_path, exist_ok=True)

    video_files = [
        f for f in os.listdir(action_video_path)
        if f.lower().endswith(video_extensions)
    ]

    video_files = sorted(video_files)

    print("\n==============================")
    print(f"Action: {action}")
    print(f"Found {len(video_files)} videos")
    print(f"Video folder: {action_video_path}")
    print("==============================")

    if len(video_files) == 0:
        print(f"⚠ No videos found for action: {action}")
        continue

    for video_counter, video_file in enumerate(video_files):

        start_time = time.time()

        print(f"\n▶ Processing {video_file}")

        full_video_path = os.path.join(action_video_path, video_file)

        cap = cv2.VideoCapture(full_video_path)

        if not cap.isOpened():
            print(f"⚠ Could not open video: {full_video_path}")
            continue

        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        print(f"Total frames: {total_frames}")

        if total_frames < 2:
            print(f"⚠ Skipping {video_file}: not enough frames")
            cap.release()
            continue

        # Safer folder naming using original video filename
        video_name_no_ext = os.path.splitext(video_file)[0]

        # Each video gets one sequence folder:
        # MP_Data/action/video_name/
        sequence_folder = os.path.join(action_data_path, video_name_no_ext)

        os.makedirs(sequence_folder, exist_ok=True)

        # Pick sequence_length evenly spaced frames
        frame_indices = np.linspace(
            0,
            total_frames - 2,
            target_frame_count,
            dtype=int
        )

        with mp_holistic.Holistic(
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5
        ) as holistic:

            for frame_num, frame_index in enumerate(frame_indices):

                cap.set(cv2.CAP_PROP_POS_FRAMES, frame_index)

                ret, frame = cap.read()

                if not ret:

                    print(f"⚠ Could not read frame {frame_index}. Saving zero keypoints.")

                    keypoints = np.zeros(1662)

                else:

                    image, results = mediapipe_detection(frame, holistic)

                    draw_styled_landmarks(image, results)

                    keypoints = extract_keypoints(results)

                    # Optional visualization
                    if debug_visualization and frame_num in frames_to_show:

                        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

                        plt.figure(figsize=(6, 6))

                        plt.imshow(image_rgb)

                        plt.axis("off")

                        plt.title(
                            f"{action} | {video_file} | extracted frame {frame_num}"
                        )

                        display(plt.gcf())

                        plt.close()

                # Always save 0.npy to sequence_length-1.npy
                npy_path = os.path.join(
                    sequence_folder,
                    f"{frame_num}.npy"
                )

                np.save(npy_path, keypoints)

        cap.release()

        elapsed_time = time.time() - start_time

        print(f"✅ Saved sequence: {sequence_folder}")
        print(f"⏱ Processing time: {elapsed_time:.2f} seconds")

==============================
Action: hello
Found 20 videos
Video folder: /content/drive/MyDrive/sign_language_detection/videos/hello
==============================

▶ Processing Hello_001.mov
Total frames: 90
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_001
⏱ Processing time: 22.72 seconds

▶ Processing Hello_002.mov
Total frames: 81
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_002
⏱ Processing time: 19.89 seconds

▶ Processing Hello_003.mov
Total frames: 79
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_003
⏱ Processing time: 7.04 seconds

▶ Processing Hello_004.mov
Total frames: 75
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_004
⏱ Processing time: 8.60 seconds

▶ Processing Hello_005.mov
Total frames: 89
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_005
⏱ Processing time: 13.24 seconds

▶ Processing Hello_006.mov
Total frames: 79
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_006
⏱ Processing time: 8.27 seconds

▶ Processing Hello_007.mov
Total frames: 91
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_007
⏱ Processing time: 6.90 seconds

▶ Processing Hello_008.mov
Total frames: 82
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_008
⏱ Processing time: 8.00 seconds

▶ Processing Hello_009.mov
Total frames: 81
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_009
⏱ Processing time: 6.94 seconds

▶ Processing Hello_010.mov
Total frames: 80
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_010
⏱ Processing time: 8.17 seconds

▶ Processing Hello_011.mov
Total frames: 84
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_011
⏱ Processing time: 13.42 seconds

▶ Processing Hello_012.mov
Total frames: 77
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_012
⏱ Processing time: 13.84 seconds

▶ Processing Hello_013.mov
Total frames: 67
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_013
⏱ Processing time: 13.11 seconds

▶ Processing Hello_014.mov
Total frames: 79
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_014
⏱ Processing time: 8.58 seconds

▶ Processing Hello_015.mov
Total frames: 81
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_015
⏱ Processing time: 13.24 seconds

▶ Processing Hello_016.mov
Total frames: 89
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_016
⏱ Processing time: 8.71 seconds

▶ Processing Hello_017.mov
Total frames: 70
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_017
⏱ Processing time: 7.41 seconds

▶ Processing Hello_018.mov
Total frames: 73
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_018
⏱ Processing time: 16.73 seconds

▶ Processing Hello_019.mov
Total frames: 89
⚠ Could not read frame 63. Saving zero keypoints.
⚠ Could not read frame 66. Saving zero keypoints.
⚠ Could not read frame 69. Saving zero keypoints.
⚠ Could not read frame 72. Saving zero keypoints.
⚠ Could not read frame 75. Saving zero keypoints.
⚠ Could not read frame 78. Saving zero keypoints.
⚠ Could not read frame 81. Saving zero keypoints.
⚠ Could not read frame 84. Saving zero keypoints.
⚠ Could not read frame 87. Saving zero keypoints.
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_019
⏱ Processing time: 19.65 seconds

▶ Processing Hello_020.MOV
Total frames: 88
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/hello/Hello_020
⏱ Processing time: 20.16 seconds

==============================
Action: thank_you
Found 20 videos
Video folder: /content/drive/MyDrive/sign_language_detection/videos/thank_you
==============================

▶ Processing Thank_you_001.MOV
Total frames: 60
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_001
⏱ Processing time: 17.42 seconds

▶ Processing Thank_you_002.MOV
Total frames: 60
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_002
⏱ Processing time: 16.95 seconds

▶ Processing Thank_you_003.MOV
Total frames: 41
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_003
⏱ Processing time: 15.67 seconds

▶ Processing Thank_you_004.MOV
Total frames: 39
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_004
⏱ Processing time: 15.23 seconds

▶ Processing Thank_you_005.MOV
Total frames: 39
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_005
⏱ Processing time: 14.32 seconds

▶ Processing Thank_you_006.MOV
Total frames: 39
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_006
⏱ Processing time: 14.52 seconds

▶ Processing Thank_you_007.MOV
Total frames: 41
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_007
⏱ Processing time: 15.92 seconds

▶ Processing Thank_you_008.MOV
Total frames: 53
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_008
⏱ Processing time: 16.46 seconds

▶ Processing Thank_you_009.MOV
Total frames: 51
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_009
⏱ Processing time: 16.05 seconds

▶ Processing Thank_you_010.MOV
Total frames: 60
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_010
⏱ Processing time: 16.19 seconds

▶ Processing Thank_you_011.MOV
Total frames: 75
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_011
⏱ Processing time: 22.49 seconds

▶ Processing Thank_you_012.MOV
Total frames: 71
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_012
⏱ Processing time: 17.53 seconds

▶ Processing Thank_you_013.MOV
Total frames: 57
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_013
⏱ Processing time: 17.06 seconds

▶ Processing Thank_you_014.MOV
Total frames: 54
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_014
⏱ Processing time: 16.85 seconds

▶ Processing Thank_you_015.MOV
Total frames: 61
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_015
⏱ Processing time: 16.57 seconds

▶ Processing Thank_you_016.MOV
Total frames: 51
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_016
⏱ Processing time: 17.33 seconds

▶ Processing Thank_you_017.MOV
Total frames: 57
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_017
⏱ Processing time: 16.25 seconds

▶ Processing Thank_you_018.MOV
Total frames: 45
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_018
⏱ Processing time: 15.25 seconds

▶ Processing Thank_you_019.MOV
Total frames: 54
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_019
⏱ Processing time: 17.47 seconds

▶ Processing Thank_you_020.MOV
Total frames: 64
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/thank_you/Thank_you_020
⏱ Processing time: 16.95 seconds

==============================
Action: see_you_later
Found 20 videos
Video folder: /content/drive/MyDrive/sign_language_detection/videos/see_you_later
==============================

▶ Processing See_you_later_001.MOV
Total frames: 71
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_001
⏱ Processing time: 17.30 seconds

▶ Processing See_you_later_002.MOV
Total frames: 56
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_002
⏱ Processing time: 16.79 seconds

▶ Processing See_you_later_003.MOV
Total frames: 71
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_003
⏱ Processing time: 18.15 seconds

▶ Processing See_you_later_004.MOV
Total frames: 92
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_004
⏱ Processing time: 19.34 seconds

▶ Processing See_you_later_005.MOV
Total frames: 70
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_005
⏱ Processing time: 16.80 seconds

▶ Processing See_you_later_006.MOV
Total frames: 63
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_006
⏱ Processing time: 16.19 seconds

▶ Processing See_you_later_007.MOV
Total frames: 66
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_007
⏱ Processing time: 17.56 seconds

▶ Processing See_you_later_008.MOV
Total frames: 59
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_008
⏱ Processing time: 16.68 seconds

▶ Processing See_you_later_009.MOV
Total frames: 344
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_009
⏱ Processing time: 21.09 seconds

▶ Processing See_you_later_010.MOV
Total frames: 73
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_010
⏱ Processing time: 17.39 seconds

▶ Processing See_you_later_011.MOV
Total frames: 79
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_011
⏱ Processing time: 18.26 seconds

▶ Processing See_you_later_012.MOV
Total frames: 54
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_012
⏱ Processing time: 16.14 seconds

▶ Processing See_you_later_013.MOV
Total frames: 95
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_013
⏱ Processing time: 18.17 seconds

▶ Processing See_you_later_014.MOV
Total frames: 76
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_014
⏱ Processing time: 18.31 seconds

▶ Processing See_you_later_015.MOV
Total frames: 115
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_015
⏱ Processing time: 18.39 seconds

▶ Processing See_you_later_016.MOV
Total frames: 95
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_016
⏱ Processing time: 19.11 seconds

▶ Processing See_you_later_017.MOV
Total frames: 73
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_017
⏱ Processing time: 19.17 seconds

▶ Processing See_you_later_018.MOV
Total frames: 80
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_018
⏱ Processing time: 20.00 seconds

▶ Processing See_you_later_019.MOV
Total frames: 52
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_019
⏱ Processing time: 16.48 seconds

▶ Processing See_you_later_020.MOV
Total frames: 55
✅ Saved sequence: /content/drive/MyDrive/sign_language_detection/MP_Data/see_you_later/See_you_later_020
⏱ Processing time: 17.22 seconds

# 6. Preprocessing Data and Creating Labels and Features

Code Block 6A

In [17]:
# Create a dictionary that maps each action label (e.g., 'hello') to a unique integer
# This is useful for converting string labels into numeric format for model training
label_map = {label: num for num, label in enumerate(actions)}

# Display the resulting label map
label_map

{'hello': 0, 'thank_you': 1, 'see_you_later': 2}

Code Block 6B

In [18]:
# Initialize lists to store sequences of keypoints and labels

sequences, labels = [], []

for action in actions:

    action_path = os.path.join(DATA_PATH, action)

    # Get all sequence folders
    sequence_folders = sorted(os.listdir(action_path))

    print(f"\nAction: {action}")
    print(f"Found sequence folders: {len(sequence_folders)}")

    for sequence in sequence_folders:

        sequence_path = os.path.join(action_path, sequence)

        # Skip non-folder files if any exist
        if not os.path.isdir(sequence_path):
            continue

        window = []

        complete_sequence = True

        for frame_num in range(sequence_length):

            npy_path = os.path.join(
                sequence_path,
                f"{frame_num}.npy"
            )

            if not os.path.exists(npy_path):

                print(
                    f"⚠ Skipping incomplete sequence: "
                    f"{action}/{sequence}, missing {frame_num}.npy"
                )

                complete_sequence = False

                break

            res = np.load(npy_path)

            window.append(res)

        if complete_sequence:

            sequences.append(window)

            labels.append(label_map[action])

# Convert to NumPy arrays
X = np.array(sequences)

# Convert labels to one-hot encoding
y = to_categorical(labels).astype(int)

print("\n==============================")
print("Dataset Loaded Successfully")
print("==============================")

print("X shape:", X.shape)
print("y shape:", y.shape)

print("Total sequences:", len(sequences))
print("Total labels:", len(labels))

Action: hello
Found sequence folders: 20

Action: thank_you
Found sequence folders: 20

Action: see_you_later
Found sequence folders: 20

==============================
Dataset Loaded Successfully
==============================
X shape: (60, 30, 1662)
y shape: (60, 3)
Total sequences: 60
Total labels: 60

Code Block 6C

In [73]:
# Split the dataset into training and testing sets

y_labels = np.argmax(y, axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y_labels
)

print("X shape:", X.shape)
print("y shape:", y.shape)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

print("Test actions:", actions[np.argmax(y_test, axis=1)])

X shape: (60, 30, 1662)
y shape: (60, 3)
X_train shape: (48, 30, 1662)
X_test shape: (12, 30, 1662)
y_train shape: (48, 3)
y_test shape: (12, 3)
Test actions: ['hello' 'see_you_later' 'thank_you' 'thank_you' 'see_you_later' 'hello'
 'see_you_later' 'hello' 'thank_you' 'thank_you' 'see_you_later' 'hello']

# 7. Building and Training an LSTM Neural Network

Code Block 7A

In [74]:
# # Build an LSTM neural network model

# from tensorflow.keras.layers import Input

# log_dir = os.path.join('Logs')
# tb_callback = TensorBoard(log_dir=log_dir)

# model = Sequential()

# model.add(Input(shape=(sequence_length, 1662)))

# model.add(LSTM(64, return_sequences=True, activation='relu'))
# model.add(LSTM(128, return_sequences=True, activation='relu'))
# model.add(LSTM(64, return_sequences=False, activation='relu'))

# model.add(Dense(64, activation='relu'))
# model.add(Dense(32, activation='relu'))
# model.add(Dense(actions.shape[0], activation='softmax'))


# Build improved LSTM neural network model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input
from tensorflow.keras.callbacks import TensorBoard

log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

model = Sequential()

# Input layer
model.add(Input(shape=(sequence_length, 1662)))

# First LSTM layer
model.add(LSTM(64, return_sequences=True))
model.add(Dropout(0.2))

# Second LSTM layer
model.add(LSTM(128, return_sequences=True))
model.add(Dropout(0.2))

# Third LSTM layer
model.add(LSTM(64, return_sequences=False))
model.add(Dropout(0.2))

# Dense layers
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))

# Output layer
model.add(Dense(actions.shape[0], activation='softmax'))

# Show model summary
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_12 (LSTM)                  │ (None, 30, 64)         │       442,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 30, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_13 (LSTM)                  │ (None, 30, 128)        │        98,816 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 30, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_14 (LSTM)                  │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 596,675 (2.28 MB)

 Trainable params: 596,675 (2.28 MB)

 Non-trainable params: 0 (0.00 B)

Code Block 7B

In [75]:
# Compile the model with the following settings:
# 'Adam' optimizer is used, which is an adaptive learning rate method commonly used in training deep learning models
model.compile(optimizer='Adam',
              # Use 'categorical_crossentropy' as the loss function, suitable for multi-class classification problems
              loss='categorical_crossentropy',
              # Track 'categorical_accuracy' during training to evaluate how well the model is classifying the correct action
              metrics=['categorical_accuracy'])

In [76]:
# Train the model using the training data
# X_train: Input data (sequences of keypoints)
# y_train: Target labels (one-hot encoded labels for the actions)
# epochs=200: The model will train for 200 epochs (iterations over the entire dataset)
# callbacks=[tb_callback]: This will use the TensorBoard callback to log training progress and metrics for visualization
# model.fit(X_train, y_train, epochs=200, callbacks=[tb_callback])
model.fit(X_train, y_train, epochs=200, callbacks=[tb_callback])

Epoch 1/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 5s 77ms/step - categorical_accuracy: 0.4375 - loss: 1.0719
Epoch 2/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 0.5417 - loss: 0.9525
Epoch 3/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.6667 - loss: 0.8180
Epoch 4/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.5417 - loss: 0.8338
Epoch 5/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - categorical_accuracy: 0.6667 - loss: 0.6575
Epoch 6/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 0.7083 - loss: 0.5759
Epoch 7/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.7292 - loss: 0.5459
Epoch 8/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.6250 - loss: 0.5144
Epoch 9/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.6875 - loss: 0.4991
Epoch 10/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 0.7083 - loss: 0.4796
Epoch 11/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.6875 - loss: 0.4849
Epoch 12/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.7083 - loss: 0.4692
Epoch 13/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.7917 - loss: 0.4555
Epoch 14/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - categorical_accuracy: 0.7083 - loss: 0.4680
Epoch 15/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - categorical_accuracy: 0.7917 - loss: 0.4555
Epoch 16/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 0.6458 - loss: 0.4778
Epoch 17/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.7500 - loss: 0.4588
Epoch 18/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.6667 - loss: 0.4581
Epoch 19/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - categorical_accuracy: 0.7500 - loss: 0.4534
Epoch 20/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - categorical_accuracy: 0.7917 - loss: 0.4529
Epoch 21/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - categorical_accuracy: 0.6875 - loss: 0.4720
Epoch 22/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.7083 - loss: 0.4605
Epoch 23/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - categorical_accuracy: 0.6875 - loss: 0.4624
Epoch 24/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.7708 - loss: 0.4419
Epoch 25/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.8333 - loss: 0.4177
Epoch 26/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.8333 - loss: 0.4089
Epoch 27/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.8333 - loss: 0.4202
Epoch 28/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.8333 - loss: 0.4042
Epoch 29/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.8750 - loss: 0.3478
Epoch 30/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.8542 - loss: 0.3541
Epoch 31/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - categorical_accuracy: 0.8750 - loss: 0.3643
Epoch 32/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - categorical_accuracy: 0.9167 - loss: 0.2703
Epoch 33/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 0.8333 - loss: 0.2979
Epoch 34/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - categorical_accuracy: 0.8125 - loss: 0.3584
Epoch 35/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 0.8750 - loss: 0.2686
Epoch 36/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.8125 - loss: 0.3473
Epoch 37/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - categorical_accuracy: 0.9375 - loss: 0.2129
Epoch 38/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - categorical_accuracy: 0.5208 - loss: 3.3756
Epoch 39/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.7083 - loss: 0.6083
Epoch 40/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 0.8333 - loss: 0.3422
Epoch 41/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - categorical_accuracy: 0.6667 - loss: 0.4781
Epoch 42/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 320ms/step - categorical_accuracy: 0.6458 - loss: 0.5509
Epoch 43/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 169ms/step - categorical_accuracy: 0.8958 - loss: 0.3654
Epoch 44/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 98ms/step - categorical_accuracy: 0.7708 - loss: 0.4288
Epoch 45/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.7083 - loss: 0.4331
Epoch 46/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.7917 - loss: 0.4157
Epoch 47/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 0.9167 - loss: 0.3388
Epoch 48/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.8333 - loss: 0.3504
Epoch 49/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 0.8750 - loss: 0.2603
Epoch 50/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - categorical_accuracy: 0.9583 - loss: 0.2484
Epoch 51/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.9583 - loss: 0.2032
Epoch 52/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.9792 - loss: 0.1582
Epoch 53/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.9375 - loss: 0.1460
Epoch 54/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - categorical_accuracy: 0.8958 - loss: 0.2465
Epoch 55/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.9583 - loss: 0.1312
Epoch 56/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 0.9167 - loss: 0.2852
Epoch 57/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.9167 - loss: 0.2315
Epoch 58/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.9167 - loss: 0.2618
Epoch 59/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 0.9375 - loss: 0.1487
Epoch 60/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - categorical_accuracy: 0.8958 - loss: 0.2037
Epoch 61/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - categorical_accuracy: 0.9583 - loss: 0.1294
Epoch 62/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 0.9792 - loss: 0.0978
Epoch 63/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.9583 - loss: 0.1370
Epoch 64/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 0.9792 - loss: 0.0736
Epoch 65/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0659
Epoch 66/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - categorical_accuracy: 1.0000 - loss: 0.0496
Epoch 67/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0388
Epoch 68/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 1.0000 - loss: 0.0477
Epoch 69/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - categorical_accuracy: 1.0000 - loss: 0.0237
Epoch 70/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - categorical_accuracy: 0.9792 - loss: 0.0412
Epoch 71/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 0.9583 - loss: 0.0751
Epoch 72/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - categorical_accuracy: 0.9375 - loss: 0.2462
Epoch 73/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 0.9375 - loss: 0.2298
Epoch 74/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 0.9792 - loss: 0.0530
Epoch 75/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.9375 - loss: 0.1777
Epoch 76/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.9792 - loss: 0.0532
Epoch 77/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.9792 - loss: 0.0766
Epoch 78/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 0.9167 - loss: 0.1422
Epoch 79/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.9792 - loss: 0.0369
Epoch 80/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 0.8958 - loss: 0.3541
Epoch 81/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 0.9167 - loss: 0.1452
Epoch 82/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.9167 - loss: 0.2114
Epoch 83/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - categorical_accuracy: 0.9375 - loss: 0.1325
Epoch 84/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0887
Epoch 85/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.9583 - loss: 0.0972
Epoch 86/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 0.9167 - loss: 0.1350
Epoch 87/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - categorical_accuracy: 0.9792 - loss: 0.0627
Epoch 88/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0516
Epoch 89/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0435
Epoch 90/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0357
Epoch 91/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - categorical_accuracy: 1.0000 - loss: 0.0359
Epoch 92/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - categorical_accuracy: 1.0000 - loss: 0.0390
Epoch 93/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - categorical_accuracy: 0.9792 - loss: 0.0557
Epoch 94/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - categorical_accuracy: 0.9792 - loss: 0.0270
Epoch 95/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - categorical_accuracy: 0.9792 - loss: 0.0397
Epoch 96/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - categorical_accuracy: 1.0000 - loss: 0.0110
Epoch 97/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - categorical_accuracy: 0.9583 - loss: 0.1017
Epoch 98/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - categorical_accuracy: 1.0000 - loss: 0.0159
Epoch 99/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 0.8958 - loss: 0.3235
Epoch 100/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 0.9583 - loss: 0.1519
Epoch 101/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0255
Epoch 102/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.9583 - loss: 0.1078
Epoch 103/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0087
Epoch 104/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0214
Epoch 105/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - categorical_accuracy: 0.9583 - loss: 0.1077
Epoch 106/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 0.9792 - loss: 0.0443
Epoch 107/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0336
Epoch 108/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - categorical_accuracy: 0.9583 - loss: 0.1119
Epoch 109/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0123
Epoch 110/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 0.9792 - loss: 0.0314
Epoch 111/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0104
Epoch 112/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 1.0000 - loss: 0.0072
Epoch 113/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 0.9792 - loss: 0.0592
Epoch 114/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0073
Epoch 115/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0070
Epoch 116/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0091
Epoch 117/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 0.9792 - loss: 0.0470
Epoch 118/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0055
Epoch 119/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0090
Epoch 120/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0134
Epoch 121/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0048
Epoch 122/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0046
Epoch 123/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0038
Epoch 124/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0048
Epoch 125/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0035
Epoch 126/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 1.0000 - loss: 0.0040
Epoch 127/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 1.0000 - loss: 0.0044
Epoch 128/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 1.0000 - loss: 0.0037
Epoch 129/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - categorical_accuracy: 1.0000 - loss: 0.0035
Epoch 130/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0046
Epoch 131/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0032
Epoch 132/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - categorical_accuracy: 1.0000 - loss: 0.0021
Epoch 133/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0024
Epoch 134/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - categorical_accuracy: 1.0000 - loss: 0.0023
Epoch 135/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0028
Epoch 136/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0024
Epoch 137/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0030
Epoch 138/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0024
Epoch 139/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - categorical_accuracy: 1.0000 - loss: 0.0025
Epoch 140/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0025
Epoch 141/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0025
Epoch 142/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0026
Epoch 143/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0023
Epoch 144/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - categorical_accuracy: 1.0000 - loss: 0.0022
Epoch 145/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - categorical_accuracy: 1.0000 - loss: 0.0015
Epoch 146/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - categorical_accuracy: 1.0000 - loss: 0.0019
Epoch 147/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - categorical_accuracy: 1.0000 - loss: 0.0017
Epoch 148/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - categorical_accuracy: 1.0000 - loss: 0.0016
Epoch 149/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - categorical_accuracy: 1.0000 - loss: 0.0015
Epoch 150/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - categorical_accuracy: 1.0000 - loss: 0.0017
Epoch 151/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - categorical_accuracy: 1.0000 - loss: 0.0016
Epoch 152/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0015
Epoch 153/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0016
Epoch 154/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - categorical_accuracy: 1.0000 - loss: 0.0038
Epoch 155/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - categorical_accuracy: 1.0000 - loss: 0.0013
Epoch 156/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0016
Epoch 157/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0014
Epoch 158/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0016
Epoch 159/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - categorical_accuracy: 1.0000 - loss: 0.0033
Epoch 160/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 1.0000 - loss: 0.0016
Epoch 161/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0011
Epoch 162/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - categorical_accuracy: 1.0000 - loss: 0.0011
Epoch 163/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0014
Epoch 164/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - categorical_accuracy: 1.0000 - loss: 0.0012
Epoch 165/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 9.7055e-04
Epoch 166/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - categorical_accuracy: 1.0000 - loss: 0.0010
Epoch 167/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - categorical_accuracy: 1.0000 - loss: 0.0010
Epoch 168/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 0.0012
Epoch 169/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 0.0012
Epoch 170/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 1.0000 - loss: 0.0011
Epoch 171/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0011
Epoch 172/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - categorical_accuracy: 1.0000 - loss: 9.6942e-04
Epoch 173/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 1.0000 - loss: 0.0012
Epoch 174/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - categorical_accuracy: 1.0000 - loss: 0.0013
Epoch 175/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - categorical_accuracy: 1.0000 - loss: 9.8134e-04
Epoch 176/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 0.0010
Epoch 177/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 8.4745e-04
Epoch 178/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - categorical_accuracy: 1.0000 - loss: 0.0011
Epoch 179/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 0.0010
Epoch 180/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - categorical_accuracy: 1.0000 - loss: 7.7297e-04
Epoch 181/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - categorical_accuracy: 1.0000 - loss: 7.6391e-04
Epoch 182/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - categorical_accuracy: 1.0000 - loss: 0.0011
Epoch 183/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - categorical_accuracy: 1.0000 - loss: 7.4358e-04
Epoch 184/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - categorical_accuracy: 1.0000 - loss: 8.4216e-04
Epoch 185/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 149ms/step - categorical_accuracy: 1.0000 - loss: 0.0010
Epoch 186/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - categorical_accuracy: 1.0000 - loss: 5.9414e-04
Epoch 187/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - categorical_accuracy: 1.0000 - loss: 0.0010
Epoch 188/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 251ms/step - categorical_accuracy: 1.0000 - loss: 7.7681e-04
Epoch 189/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - categorical_accuracy: 1.0000 - loss: 7.1491e-04
Epoch 190/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - categorical_accuracy: 1.0000 - loss: 7.9118e-04
Epoch 191/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 7.8978e-04
Epoch 192/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 9.0100e-04
Epoch 193/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - categorical_accuracy: 1.0000 - loss: 8.3658e-04
Epoch 194/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - categorical_accuracy: 1.0000 - loss: 9.1337e-04
Epoch 195/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - categorical_accuracy: 1.0000 - loss: 6.1792e-04
Epoch 196/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - categorical_accuracy: 1.0000 - loss: 6.6237e-04
Epoch 197/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - categorical_accuracy: 1.0000 - loss: 6.8447e-04
Epoch 198/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - categorical_accuracy: 1.0000 - loss: 6.9962e-04
Epoch 199/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - categorical_accuracy: 1.0000 - loss: 5.6639e-04
Epoch 200/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - categorical_accuracy: 1.0000 - loss: 7.1446e-04

# 8. Making Predictions

Code Block 8A

In [79]:
# Make predictions on the test set

y_pred = model.predict(X_test, verbose=0)

print("y_pred shape:", y_pred.shape)

y_pred shape: (12, 3)

Code Block 8B

In [80]:
# Show predictions for all test samples

for i in range(len(y_pred)):
    predicted_action = actions[np.argmax(y_pred[i])]
    actual_action = actions[np.argmax(y_test[i])]

    print(f"Sample {i}")
    print("Predicted:", predicted_action)
    print("Actual:", actual_action)
    print("Probabilities:", y_pred[i])
    print()

Sample 0
Predicted: hello
Actual: hello
Probabilities: [9.9978852e-01 2.0738257e-04 4.0106534e-06]

Sample 1
Predicted: see_you_later
Actual: see_you_later
Probabilities: [2.186239e-04 2.313279e-04 9.995501e-01]

Sample 2
Predicted: thank_you
Actual: thank_you
Probabilities: [4.8749815e-04 9.9942362e-01 8.8929060e-05]

Sample 3
Predicted: thank_you
Actual: thank_you
Probabilities: [5.2975659e-04 9.9938107e-01 8.9136527e-05]

Sample 4
Predicted: see_you_later
Actual: see_you_later
Probabilities: [2.1974425e-04 2.3234422e-04 9.9954796e-01]

Sample 5
Predicted: hello
Actual: hello
Probabilities: [9.9980497e-01 1.9104598e-04 3.8825547e-06]

Sample 6
Predicted: see_you_later
Actual: see_you_later
Probabilities: [2.2156195e-04 2.3529811e-04 9.9954319e-01]

Sample 7
Predicted: hello
Actual: hello
Probabilities: [9.9974751e-01 2.4713704e-04 5.2312676e-06]

Sample 8
Predicted: thank_you
Actual: thank_you
Probabilities: [4.828351e-04 9.994282e-01 8.890217e-05]

Sample 9
Predicted: thank_you
Actual: thank_you
Probabilities: [5.795120e-04 9.993266e-01 9.392873e-05]

Sample 10
Predicted: see_you_later
Actual: see_you_later
Probabilities: [2.2299770e-04 2.3668831e-04 9.9954033e-01]

Sample 11
Predicted: hello
Actual: hello
Probabilities: [9.9981004e-01 1.8541043e-04 4.5757411e-06]

Code Block 8C

In [81]:
# Compare predicted labels and actual labels

predicted_labels = np.argmax(y_pred, axis=1)
actual_labels = np.argmax(y_test, axis=1)

print("Predicted labels:", predicted_labels)
print("Actual labels:", actual_labels)

print("\nPredicted actions:", actions[predicted_labels])
print("Actual actions:", actions[actual_labels])

test_accuracy = np.mean(predicted_labels == actual_labels)
print("Test accuracy:", test_accuracy)

Predicted labels: [0 2 1 1 2 0 2 0 1 1 2 0]
Actual labels: [0 2 1 1 2 0 2 0 1 1 2 0]

Predicted actions: ['hello' 'see_you_later' 'thank_you' 'thank_you' 'see_you_later' 'hello'
 'see_you_later' 'hello' 'thank_you' 'thank_you' 'see_you_later' 'hello']
Actual actions: ['hello' 'see_you_later' 'thank_you' 'thank_you' 'see_you_later' 'hello'
 'see_you_later' 'hello' 'thank_you' 'thank_you' 'see_you_later' 'hello']
Test accuracy: 1.0

# 9. Saving Weights

Code Block 9A

In [82]:
# Define the file path where the trained model will be saved
# The model will be saved as a .h5 file (HDF5 format), which stores the model architecture, weights, and optimizer state
model_path = os.path.join(base_dir, 'my_model.keras')

# Save the trained model to the specified path
# This allows you to later load the model for inference or continue training
model.save(model_path)

Code Block 9B

In [83]:
# Load the saved model from the specified file path
model_path = os.path.join(base_dir, 'my_model.keras')
# 'model_path' points to the location where the model was previously saved (e.g., 'action.h5')
# The model is loaded along with its architecture, weights, and optimizer state, making it ready for inference or further training
model = load_model(model_path)

# 10. Evaluating Using a Confusion Matrix and Accuracy

Code Block 10A

In [84]:
# Predict on test set and convert probabilities to class labels

y_pred_probs = model.predict(X_test, verbose=0)

y_true = np.argmax(y_test, axis=1).tolist()
y_pred_labels = np.argmax(y_pred_probs, axis=1).tolist()

print("True actions:", actions[y_true])
print("Predicted actions:", actions[y_pred_labels])

True actions: ['hello' 'see_you_later' 'thank_you' 'thank_you' 'see_you_later' 'hello'
 'see_you_later' 'hello' 'thank_you' 'thank_you' 'see_you_later' 'hello']
Predicted actions: ['hello' 'see_you_later' 'thank_you' 'thank_you' 'see_you_later' 'hello'
 'see_you_later' 'hello' 'thank_you' 'thank_you' 'see_you_later' 'hello']

Code Block 10B

In [85]:
# Calculate multilabel confusion matrix

conf_matrix = multilabel_confusion_matrix(y_true, y_pred_labels)

for idx, matrix in enumerate(conf_matrix):
    print(f"\nConfusion Matrix for class '{actions[idx]}':")
    df = pd.DataFrame(
        matrix,
        index=["Actual Negative", "Actual Positive"],
        columns=["Predicted Negative", "Predicted Positive"]
    )
    print(df)

Confusion Matrix for class 'hello':
                 Predicted Negative  Predicted Positive
Actual Negative                   8                   0
Actual Positive                   0                   4

Confusion Matrix for class 'thank_you':
                 Predicted Negative  Predicted Positive
Actual Negative                   8                   0
Actual Positive                   0                   4

Confusion Matrix for class 'see_you_later':
                 Predicted Negative  Predicted Positive
Actual Negative                   8                   0
Actual Positive                   0                   4

Code Block 10C

In [86]:
# Calculate accuracy score

accuracy = accuracy_score(y_true, y_pred_labels)
print("Accuracy:", accuracy)

Accuracy: 1.0

In [87]:
# ============================================
# CREATE TABLES FOR REPORT
# ============================================

import pandas as pd
import numpy as np

# --------------------------------------------
# OVERALL RESULTS
# --------------------------------------------

predicted_labels = np.argmax(y_pred_probs, axis=1)
actual_labels = np.argmax(y_test, axis=1)

correct = np.sum(predicted_labels == actual_labels)
wrong = len(actual_labels) - correct

accuracy = (correct / len(actual_labels)) * 100

overall_results_df = pd.DataFrame({
    "Correct": [f"{correct} / {len(actual_labels)}"],
    "Wrong": [f"{wrong} / {len(actual_labels)}"],
    "Accuracy": [f"{accuracy:.2f}%"]
})

print("\n===================================")
print("OVERALL RESULTS")
print("===================================")

display(overall_results_df)

# --------------------------------------------
# DATASET TABLE
# --------------------------------------------

dataset_df = pd.DataFrame({
    "Total Videos": [len(X)],
    "Training Videos": [len(X_train)],
    "Testing Videos": [len(X_test)]
})

print("\n===================================")
print("DATASET")
print("===================================")

display(dataset_df)

# --------------------------------------------
# PER-SIGN ACCURACY TABLE
# --------------------------------------------

per_sign_results = []

for idx, action in enumerate(actions):

    tested = np.sum(actual_labels == idx)

    correct_sign = np.sum(
        (actual_labels == idx) &
        (predicted_labels == idx)
    )

    if tested > 0:
        sign_accuracy = (correct_sign / tested) * 100
    else:
        sign_accuracy = 0

    per_sign_results.append({
        "Sign": action,
        "Tested": tested,
        "Correct": correct_sign,
        "Accuracy %": f"{sign_accuracy:.2f}%"
    })

per_sign_df = pd.DataFrame(per_sign_results)

print("\n===================================")
print("PER-SIGN ACCURACY")
print("===================================")

display(per_sign_df)

===================================
OVERALL RESULTS
===================================

   Correct   Wrong Accuracy
0  12 / 12  0 / 12  100.00%

===================================
DATASET
===================================

   Total Videos  Training Videos  Testing Videos
0            60               48              12

===================================
PER-SIGN ACCURACY
===================================

            Sign  Tested  Correct Accuracy %
0          hello       4        4    100.00%
1      thank_you       4        4    100.00%
2  see_you_later       4        4    100.00%

# 11. Testing with Videos

Code Block 11A

In [93]:
# ==============================
# 11. Testing with Multiple Videos
# ==============================

base_test_path = "/content/drive/MyDrive/sign_language_detection/test_videos"

# NEW OUTPUT FOLDER
output_folder = "/content/drive/MyDrive/sign_language_detection/output_videos"

os.makedirs(base_test_path, exist_ok=True)
os.makedirs(output_folder, exist_ok=True)

# Find all test videos
test_videos = sorted([
    f for f in os.listdir(base_test_path)
    if f.lower().endswith((".mp4", ".mov", ".avi", ".mkv"))
])

print("Found test videos:")
for video in test_videos:
    print(video)

# Random colors for probability bars
colors = [tuple(random.randint(0, 255) for _ in range(3)) for _ in actions]


def prob_viz(res, actions, input_frame, colors):

    output_frame = input_frame.copy()

    for num, prob in enumerate(res):

        color = colors[num]

        cv2.rectangle(
            output_frame,
            (0, 60 + num * 40),
            (int(prob * 100), 90 + num * 40),
            color,
            -1
        )

        cv2.putText(
            output_frame,
            actions[num],
            (0, 85 + num * 40),
            cv2.FONT_HERSHEY_SIMPLEX,
            1,
            (255, 255, 255),
            2,
            cv2.LINE_AA
        )

    return output_frame


# Mediapipe setup
mp_holistic = mp.solutions.holistic

# Process all test videos
for video_index, test_video in enumerate(test_videos, start=1):

    print("\n===================================")
    print(f"Processing video: {test_video}")
    print("===================================")

    input_video_path = os.path.join(base_test_path, test_video)

    # Save outputs in NEW output folder
    output_video_name = f"output_video_{video_index}.mp4"

    output_video_path = os.path.join(
        output_folder,
        output_video_name
    )

    # Detection variables
    sequence = []
    sentence = []
    predictions = []

    threshold = 0.5

    # Load video
    cap = cv2.VideoCapture(input_video_path)

    if not cap.isOpened():
        print(f"⚠ Could not open video: {input_video_path}")
        continue

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = cap.get(cv2.CAP_PROP_FPS)

    # Safety fallback
    if fps == 0 or np.isnan(fps):
        fps = 30

    print("Input video:", input_video_path)
    print("Output video:", output_video_path)

    # Output video setup
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")

    out = cv2.VideoWriter(
        output_video_path,
        fourcc,
        fps,
        (width, height)
    )

    if not out.isOpened():
        print("⚠ Could not create output video writer.")
        continue

    with mp_holistic.Holistic(
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5
    ) as holistic:

        while cap.isOpened():

            ret, frame = cap.read()

            if not ret:
                break

            # Detection
            image, results = mediapipe_detection(frame, holistic)

            draw_styled_landmarks(image, results)

            # Extract keypoints
            keypoints = extract_keypoints(results)

            # Keep latest sequence_length frames
            sequence.append(keypoints)

            sequence = sequence[-sequence_length:]

            # Predict when enough frames collected
            if len(sequence) == sequence_length:

                res = model.predict(
                    np.expand_dims(sequence, axis=0),
                    verbose=0
                )[0]

                predicted_index = np.argmax(res)

                predictions.append(predicted_index)

                # Smooth predictions
                if len(predictions) >= 10:

                    if np.all(
                        np.array(predictions[-10:]) == predicted_index
                    ):

                        if res[predicted_index] > threshold:

                            predicted_action = actions[predicted_index]

                            if (
                                len(sentence) == 0
                                or predicted_action != sentence[-1]
                            ):

                                sentence.append(predicted_action)

                # Keep last 5 predictions
                if len(sentence) > 5:
                    sentence = sentence[-5:]

                # Add probability bars
                image = prob_viz(
                    res,
                    actions,
                    image,
                    colors
                )

            # Add top prediction text
            cv2.rectangle(
                image,
                (0, 0),
                (width, 40),
                (245, 117, 16),
                -1
            )

            cv2.putText(
                image,
                " ".join(sentence),
                (3, 30),
                cv2.FONT_HERSHEY_SIMPLEX,
                1,
                (255, 255, 255),
                2,
                cv2.LINE_AA
            )

            # Save output frame
            out.write(image)

    # Release resources
    cap.release()
    out.release()

    print(f"✅ Done. Output saved to: {output_video_path}")

print("\n===================================")
print("ALL VIDEOS PROCESSED")
print("===================================")

Found test videos:
test_video_1.mov
test_video_2.mov

===================================
Processing video: test_video_1.mov
===================================
Input video: /content/drive/MyDrive/sign_language_detection/test_videos/test_video_1.mov
Output video: /content/drive/MyDrive/sign_language_detection/output_videos/output_video_1.mp4
✅ Done. Output saved to: /content/drive/MyDrive/sign_language_detection/output_videos/output_video_1.mp4

===================================
Processing video: test_video_2.mov
===================================
Input video: /content/drive/MyDrive/sign_language_detection/test_videos/test_video_2.mov
Output video: /content/drive/MyDrive/sign_language_detection/output_videos/output_video_2.mp4
✅ Done. Output saved to: /content/drive/MyDrive/sign_language_detection/output_videos/output_video_2.mp4

===================================
ALL VIDEOS PROCESSED
===================================